version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "127.0.0.1:8000:8000" # Solo accesible desde dentro del VPS (Nginx lo alcanzará aquí)
    env_file:
      - .env

volumes:
  static_volume:
  media_volume: