# Generated by Django 5.2.4 on 2025-07-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300, null=True)),
                ('fecha', models.DateTimeField(null=True)),
                ('lugar', models.CharField(max_length=100)),
                ('tenida', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=300)),
                ('fecha_licencia', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomberos.citacion')),
            ],
            options={
                'permissions': [('check_licencias', 'Puede revisar todas las licencias')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('contacto', models.IntegerField(null=True)),
                ('imagen', models.ImageField(default='fotos_perfil/user.jpg', upload_to='fotos_perfil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bombero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
