# Generated by Django 5.2.4 on 2025-07-21 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0002_emergencia_listaasistencia_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oficios_direccion', 'Oficios de Dirección'), ('oficios_capitania', 'Oficios de Capitanía'), ('citaciones_comandancia', 'Citaciones de Comandancia'), ('resoluciones_consejo_disciplina', 'Resoluciones Consejo de Disciplina'), ('resoluciones_consejo_superior', 'Resoluciones Consejo Superior de Disciplina'), ('circulares_escuela', 'Circulares Escuela de Bomberos de Quillota'), ('correspondencia_recibida', 'Correspondencia Recibida'), ('ordenes_dia_compania', 'Órdenes del Día de Compañía'), ('ordenes_dia_comandancia', 'Órdenes del Día de Comandancia'), ('informativos_direccion', 'Informativos Dirección'), ('guardias_nocturnas', 'Guardias Nocturnas'), ('reglamentos', 'Reglamentos')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_upload_oficios_direccion', 'Puede subir Oficios de Dirección'), ('can_upload_oficios_capitania', 'Puede subir Oficios de Capitanía'), ('can_upload_citaciones_comandancia', 'Puede subir Citaciones de Comandancia'), ('can_upload_resoluciones_consejo_disciplina', 'Puede subir Resoluciones Consejo de Disciplina'), ('can_upload_resoluciones_consejo_superior', 'Puede subir Resoluciones Consejo Superior de Disciplina'), ('can_upload_circulares_escuela', 'Puede subir Circulares Escuela de Bomberos de Quillota'), ('can_upload_correspondencia_recibida', 'Puede subir Correspondencia Recibida'), ('can_upload_ordenes_dia_compania', 'Puede subir Órdenes del Día de Compañía'), ('can_upload_ordenes_dia_comandancia', 'Puede subir Órdenes del Día de Comandancia'), ('can_upload_informativos_direccion', 'Puede subir Informativos Dirección'), ('can_upload_guardias_nocturnas', 'Puede subir Guardias Nocturnas'), ('can_upload_reglamentos', 'Puede subir Reglamentos')],
            },
        ),
    ]
