# Generated by Django 5.2.4 on 2025-07-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0003_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos/'),
        ),
    ]
