# Generated by Django 5.2.4 on 2026-03-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0008_item_sala_loginventario_item_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='is_declarado',
            field=models.BooleanField(default=False),
        ),
    ]
