# Generated by Django 5.2.4 on 2026-03-27 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0009_emergencia_is_declarado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_excepcion', models.CharField(choices=[('Suspendido', 'Suspendido'), ('Licencia Corrida', 'Licencia Corrida'), ('Separado', 'Separado'), ('Licencia Extendida', 'Licencia Extendida')], max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_asistencia', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de Asistencia',
                'verbose_name_plural': 'Excepciones de Asistencia',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
