# Generated by Django 5.2.4 on 2026-06-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0010_excepcionasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='responsable',
            field=models.CharField(blank=True, choices=[('director', 'Director'), ('capitan', 'Capitán'), ('secretario', 'Secretario'), ('tesorero', 'Tesorero'), ('teniente_1', 'Teniente 1°'), ('teniente_2', 'Teniente 2°'), ('teniente_3', 'Teniente 3°'), ('ayudante', 'Ayudante')], max_length=50, null=True),
        ),
    ]
