# Generated by Django 5.2.4 on 2026-06-11 18:08

from django.db import migrations


def create_default_tenant_and_module(apps, schema_editor):
    Tenant = apps.get_model('bomberos', 'Tenant')
    Modulo = apps.get_model('bomberos', 'Modulo')
    TenantModulo = apps.get_model('bomberos', 'TenantModulo')
    UserProfile = apps.get_model('bomberos', 'UserProfile')

    # 1. Create default Tenant
    tenant, created = Tenant.objects.get_or_create(
        subdominio='quillota',
        defaults={'nombre': 'Tercera Compañía Quillota'}
    )

    # 2. Create default Modulo
    modulo, created = Modulo.objects.get_or_create(
        clave='inventario',
        defaults={
            'nombre': 'Inventario',
            'descripcion': 'Gestión de salas, ítems y bitácora de movimientos.'
        }
    )

    # 3. Associate Modulo with Tenant (activate it)
    TenantModulo.objects.get_or_create(
        tenant=tenant,
        modulo=modulo,
        defaults={'is_active': True}
    )

    # 4. Associate all existing UserProfiles with the default Tenant
    UserProfile.objects.filter(tenant__isnull=True).update(tenant=tenant)


def reverse_default_tenant_and_module(apps, schema_editor):
    Tenant = apps.get_model('bomberos', 'Tenant')
    Modulo = apps.get_model('bomberos', 'Modulo')
    TenantModulo = apps.get_model('bomberos', 'TenantModulo')
    UserProfile = apps.get_model('bomberos', 'UserProfile')

    tenant = Tenant.objects.filter(subdominio='quillota').first()
    if tenant:
        UserProfile.objects.filter(tenant=tenant).update(tenant=None)
        TenantModulo.objects.filter(tenant=tenant).delete()
        tenant.delete()

    Modulo.objects.filter(clave='inventario').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0012_modulo_tenant_userprofile_tenant_tenantmodulo'),
    ]

    operations = [
        migrations.RunPython(create_default_tenant_and_module, reverse_default_tenant_and_module),
    ]

