# Generated by Django 5.2.4 on 2026-06-11 18:15

from django.db import migrations


def create_archivos_and_tesoreria_modules(apps, schema_editor):
    Tenant = apps.get_model('bomberos', 'Tenant')
    Modulo = apps.get_model('bomberos', 'Modulo')
    TenantModulo = apps.get_model('bomberos', 'TenantModulo')

    tenant = Tenant.objects.filter(subdominio='quillota').first()
    if not tenant:
        return

    # 1. Create Modulo Archivos
    mod_archivos, _ = Modulo.objects.get_or_create(
        clave='archivos',
        defaults={
            'nombre': 'Archivos',
            'descripcion': 'Repositorio de reglamentos, oficios, circulares y órdenes del día.'
        }
    )

    # 2. Create Modulo Tesoreria
    mod_tesoreria, _ = Modulo.objects.get_or_create(
        clave='tesoreria',
        defaults={
            'nombre': 'Tesorería',
            'descripcion': 'Gestión de comprobantes, cuotas mensuales y control de morosidad.'
        }
    )

    # 3. Associate Modulo Archivos with Tenant
    TenantModulo.objects.get_or_create(
        tenant=tenant,
        modulo=mod_archivos,
        defaults={'is_active': True}
    )

    # 4. Associate Modulo Tesoreria with Tenant
    TenantModulo.objects.get_or_create(
        tenant=tenant,
        modulo=mod_tesoreria,
        defaults={'is_active': True}
    )


def reverse_archivos_and_tesoreria_modules(apps, schema_editor):
    Tenant = apps.get_model('bomberos', 'Tenant')
    Modulo = apps.get_model('bomberos', 'Modulo')
    TenantModulo = apps.get_model('bomberos', 'TenantModulo')

    tenant = Tenant.objects.filter(subdominio='quillota').first()
    if tenant:
        TenantModulo.objects.filter(tenant=tenant, modulo__clave__in=['archivos', 'tesoreria']).delete()

    Modulo.objects.filter(clave__in=['archivos', 'tesoreria']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0013_auto_20260611_1408'),
    ]

    operations = [
        migrations.RunPython(create_archivos_and_tesoreria_modules, reverse_archivos_and_tesoreria_modules),
    ]

