# Generated by Django 5.2.4 on 2026-06-11 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0014_auto_20260611_1415'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bomberos', models.ManyToManyField(related_name='guardias_bombero', to=settings.AUTH_USER_MODEL)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_conductor', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_creadas', to=settings.AUTH_USER_MODEL)),
                ('oficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardias_oficial', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias', to='bomberos.tenant')),
            ],
            options={
                'verbose_name': 'Guardia',
                'verbose_name_plural': 'Guardias',
                'ordering': ['fecha'],
                'unique_together': {('tenant', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudReemplazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reemplazo', to='bomberos.guardia')),
                ('reemplazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reemplazo_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reemplazo_pedidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Reemplazo',
                'verbose_name_plural': 'Solicitudes de Reemplazo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
