# Generated by Django 5.2.4 on 2026-06-11 18:32

from django.db import migrations


def create_guardias_module(apps, schema_editor):
    Tenant = apps.get_model('bomberos', 'Tenant')
    Modulo = apps.get_model('bomberos', 'Modulo')
    TenantModulo = apps.get_model('bomberos', 'TenantModulo')

    tenant = Tenant.objects.filter(subdominio='quillota').first()
    if not tenant:
        return

    # 1. Create Modulo Guardias
    modulo, _ = Modulo.objects.get_or_create(
        clave='guardias',
        defaults={
            'nombre': 'Guardias',
            'descripcion': 'Planificación de turnos de guardia, descargas en PDF y solicitudes de reemplazo.'
        }
    )

    # 2. Associate Modulo with Tenant
    TenantModulo.objects.get_or_create(
        tenant=tenant,
        modulo=modulo,
        defaults={'is_active': True}
    )


def reverse_guardias_module(apps, schema_editor):
    Tenant = apps.get_model('bomberos', 'Tenant')
    Modulo = apps.get_model('bomberos', 'Modulo')
    TenantModulo = apps.get_model('bomberos', 'TenantModulo')

    tenant = Tenant.objects.filter(subdominio='quillota').first()
    if tenant:
        TenantModulo.objects.filter(tenant=tenant, modulo__clave='guardias').delete()

    Modulo.objects.filter(clave='guardias').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0015_userprofile_is_conductor_guardia_solicitudreemplazo'),
    ]

    operations = [
        migrations.RunPython(create_guardias_module, reverse_guardias_module),
    ]

