# Generated by Django 5.2.4 on 2026-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0016_auto_20260611_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='es_borrador',
            field=models.BooleanField(default=False),
        ),
    ]
