# Generated by Django 5.2.4 on 2026-06-11 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0017_guardia_es_borrador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_lanzamiento', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='bomberos.tenant')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-fecha_lanzamiento', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FormularioCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('tipo_campo', models.CharField(choices=[('numerico', 'Numérico'), ('texto', 'Texto'), ('seleccion_multiple', 'Selección Múltiple'), ('seleccion_unica', 'Selección Única')], max_length=50)),
                ('obligatorio', models.BooleanField(default=True)),
                ('opciones', models.JSONField(blank=True, default=list, help_text='Lista de opciones (array de strings) para selección')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='bomberos.formulario')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='bomberos.formulario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_formularios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de Formulario',
                'verbose_name_plural': 'Respuestas de Formulario',
                'ordering': ['-creado_en'],
                'unique_together': {('formulario', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='FormularioRespuestaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(help_text='Valor ingresado por el usuario (número, texto o array de opciones)')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_valores', to='bomberos.formulariocampo')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='bomberos.formulariorespuesta')),
            ],
            options={
                'verbose_name': 'Valor de Respuesta',
                'verbose_name_plural': 'Valores de Respuesta',
                'unique_together': {('respuesta', 'campo')},
            },
        ),
    ]
