# Generated by Django 5.2.4 on 2026-06-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0018_formulario_formulariocampo_formulariorespuesta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('contexto', models.CharField(choices=[('incendio', 'Incendio'), ('rescate', 'Rescate'), ('ejercicio', 'Ejercicio'), ('otro', 'Otro')], max_length=50)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidentes', to='bomberos.userprofile')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accidente',
                'verbose_name_plural': 'Accidentes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('examenes', 'Exámenes'), ('fichas_medicas', 'Fichas Médicas'), ('certificados_aptitud', 'Certificados de Aptitud'), ('otros', 'Otros')], max_length=50)),
                ('archivo', models.FileField(upload_to='salud/expedientes/')),
                ('fecha_documento', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_salud', to='bomberos.userprofile')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_salud_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente de Salud',
                'verbose_name_plural': 'Expedientes de Salud',
                'ordering': ['-fecha_documento', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hito', models.DateField()),
                ('tipo_accion', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='salud/accidentes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bomberos.accidente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Accidente',
                'verbose_name_plural': 'Movimientos de Accidente',
                'ordering': ['-fecha_hito', '-creado_en'],
            },
        ),
    ]
