# Generated by Django 5.2.4 on 2026-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bomberos', '0019_accidente_expedientesalud_movimientoaccidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='licencias/'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
    ]
